import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SwapWidget } from "@uniswap/widgets";
import "@uniswap/widgets/fonts.css";

import { useProvider, useSigner } from "wagmi";

const Home: NextPage = () => {
  const provider = useSigner().data?.provider;

  const jsonRpcUrlMap = {
    1: "https://eth-goerli.g.alchemy.com/v2/3i8jCezRXagBt41owabyHL1nxambxJHr",
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <SwapWidget width={500} jsonRpcUrlMap={jsonRpcUrlMap} />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
